name: Setup Gitflow

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  setup-gitflow:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Ensure repository default branch is 'main'
        uses: actions/github-script@v7
        with:
          script: |
            const repo = await github.rest.repos.get({ owner: context.repo.owner, repo: context.repo.repo });
            const defaultBranch = repo.data.default_branch;
            if (defaultBranch !== 'main') {
              core.setFailed(`Repository default branch is '${defaultBranch}'. This setup requires the default branch to be 'main'. Create a 'main' branch or change the repository default branch to 'main' before running this workflow.`);
            }

      - name: Checkout default branch
        uses: actions/checkout@v6
        with:
          ref: main

      - name: Create develop branch from main
        run: |
          set -e
          git fetch origin main:main
          if git show-ref --verify --quiet refs/heads/develop; then
            echo "develop branch already exists"
          else
            git checkout -b develop main
            git push origin develop
          fi

      - name: Create release branch template
        run: |
          if git show-ref --verify --quiet refs/heads/release/template; then
            echo "release/template exists"
          else
            git checkout -b release/template develop
            git push origin release/template
          fi