name: Setup Labels

on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  setup-labels:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: Ensure repository default branch is 'main'
        uses: actions/github-script@v7
        with:
          script: |
            const repo = await github.rest.repos.get({ owner: context.repo.owner, repo: context.repo.repo });
            const defaultBranch = repo.data.default_branch;
            if (defaultBranch !== 'main') {
              core.setFailed(`Repository default branch is '${defaultBranch}'. This setup requires the default branch to be 'main'. Create a 'main' branch or change the repository default branch to 'main' before running this workflow.`);
            }

      - name: Create standard labels
        uses: actions/github-script@v7
        with:
          script: |
            const labels = [
              { name: 'bug', color: 'd73a4a', description: 'Something is not working' },
              { name: 'enhancement', color: 'a2eeef', description: 'New feature or request' },
              { name: 'documentation', color: '0075ca', description: 'Improvements or additions to documentation' },
              { name: 'dependencies', color: '6f42c1', description: 'Dependency update (automated)' },
              { name: 'chore', color: 'cfd3d7', description: 'Housekeeping tasks' },
              { name: 'release', color: '0e8a16', description: 'Release related' }
            ];
            for (const label of labels) {
              try {
                await github.rest.issues.createLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: label.name,
                  color: label.color,
                  description: label.description
                });
              } catch (err) {
                if (err.status === 422) {
                  // label exists
                } else {
                  throw err;
                }
              }
            }