name: Setup Branch Protection

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  apply-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure repository default branch is 'main'
        uses: actions/github-script@v7
        with:
          script: |
            const repo = await github.rest.repos.get({ owner: context.repo.owner, repo: context.repo.repo });
            const defaultBranch = repo.data.default_branch;
            if (defaultBranch !== 'main') {
              core.setFailed(`Repository default branch is '${defaultBranch}'. This setup requires the default branch to be 'main'. Create a 'main' branch or change the repository default branch to 'main' before running this workflow.`);
            }

      - name: Apply protections for main and develop
        uses: actions/github-script@v7
        with:
          script: |
            const branches = ['main','develop'];
            for (const branch of branches) {
              const params = {
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: branch,
                required_status_checks: {
                  strict: true,
                  contexts: ['ci','build']
                },
                enforce_admins: true,
                required_pull_request_reviews: {
                  dismiss_stale_reviews: true,
                  required_approving_review_count: 1
                },
                restrictions: null
              };
              try {
                await github.rest.repos.updateBranchProtection(params);
              } catch (err) {
                throw err;
              }
            }