name: Validate Pull Request Template Usage

on:
  pull_request:
    types: [opened, edited]

jobs:
  validate_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR body for required sections
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const body = pr.body || '';
            const required = ['## Summary', '## Related Issue', '## Checklist'];
            const missing = required.filter(h => !new RegExp(h.replace(/[#\-]/g,''), 'i').test(body));
            if (missing.length) {
              await github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: `Please complete the pull request template sections: ${missing.join(', ')}`
              });
            }
